### ISSUE TITLE
Fails to run on webtask.io due to compilation error in nodemailer

### ISSUE THREAD

**Issue by mpilar** [mpilar/wt-mmt#1]
It's returning the following:

```
{
    "code": 400,
    "error": "Unexpected token ...",
    "message": "Compilation failed: Unexpected token ...",
    "stack": "SyntaxError: Unexpected token ...\n    at exports.runInThisContext (vm.js:53:16)\n    at Module._compile (module.js:373:25)\n    at Module._compile (/data/sandbox/lib/module.js:127:21)\n    at Object.Module._extensions..js (module.js:416:10)\n    at Module.load (module.js:343:32)\n    at Function.Module._load (module.js:300:12)\n    at Module.require (module.js:353:17)\n    at require (internal/module.js:12:17)\n    at Object.<anonymous> (/data/_verquire/nodemailer/4.0.1/node_modules/nodemailer/lib/nodemailer.js:3:16)\n    at Module._compile (module.js:409:26)"
}
```

Probably switching to sendgrid is the best option.

**Comment by mpilar** [comment]
Fixed by f655811
